version: "3"

services:
  app:
    image: golang:1.9.2
    volumes:
      - .:/go/src/github.com/chadit/GoSamples/file/parser
    working_dir: /go/src/github.com/chadit/GoSamples/file/parser
    command: go run main.go keyword.go resolver.go text.go